services:
  - type: web
    name: edufocus-system
    env: node
    plan: free
    buildCommand: npm install --production=false --prefix client && npm run build --prefix client && npm install --prefix server
    startCommand: node server/server.js
    envVars:
      - key: NODE_VERSION
        value: 20.x
      - key: NODE_ENV
        value: production
